### PR TITLE
Update static files cache TTL

### PR DESCRIPTION
**Pull request by tbille**
Update default cache control header for static files to a year.

https://flask.palletsprojects.com/en/1.1.x/config/#SEND_FILE_MAX_AGE_DEFAULT

### CODE REVIEW

**Review by jkfran — APPROVED** [review]
LGTM!

**Comment by jkfran** [comment]
Toto, what are the motivations for this change?

**Comment by tbille** [comment]
@jkfran static content can be cached for ever, we have a hash that would show if there is an update. This will avoid requesting too often the same assets from the same browser.

eg. https://charmhub.io/static/js/dist/base.js?v=4dd35c4

**Comment by jkfran** [comment]
> @jkfran static content can be cached for ever, we have a hash that would show if there is an update. This will avoid requesting too often the same assets from the same browser.
> 
> eg. https://charmhub.io/static/js/dist/base.js?v=4dd35c4

It's what I was thinking! Cool! I'm wondering if caching all the static files and their versions for a long time could cause a space problem for IS

**Pull request merged**
