### PR TITLE
Pin gevent to 20.5.1 (Last version)

### PR DESCRIPTION
**Pull request by jkfran**
# Done
Pin gevent to version 20.5.1, fixes https://github.com/canonical-web-and-design/canonicalwebteam.flask-base/issues/30

### CODE REVIEW

**Comment by jkfran** [comment]
@nottrobin should we consider pinning any other dependency?

**Comment by nottrobin** [comment]
@jkfran the only one I was thinking was maybe talisker, as new releases of that might sometimes break stuff. But have new releases of Talisker broken us recently? @tbille do you know?

On the whole, no I don't think we should be pinning unless we specifically anticipate problems.

**Comment by tbille** [comment]
@nottrobin @jkfran the reason that we could keep gevent pinned is that we are basically the main users of gevent with talikser. We could argue that not pinning it could also be a good way to signal the talisker project that the newest gevent version is not supported anymore, but this implies that on our side we would block all of our websites from being deployed. 

But also talikser requires a version [`gevent>=1.5.0`](https://github.com/canonical-ols/talisker/blob/master/setup.py#L158).

Also I am not sure what happened here but gevent went from [`1.5.0` to `20.4.0`](https://pypi.org/project/gevent/#history)

**Comment by carkod** [comment]
@jkfran rebase

**Pull request merged**
