### PR TITLE
Flask sites should always set SECRET_KEY

### PR DESCRIPTION
**Pull request by nottrobin**
Even if we know a site doesn't use it, we should set this key as it's very
easy for someone to come along later and add features that rely on it
without remembering to set up the secret key.

We should then add a default insecure secret key setting into `.env` in our
projects.

### CODE REVIEW

**Comment by nottrobin** [comment]
A first step towards https://github.com/canonical-web-and-design/web-squad/issues/2609

**Comment by jpmartinspt** [comment]
This looks good, should we just make people aware that if they bump the package they also need to update the deployment-configs?

**Comment by nottrobin** [comment]
@jpmartinspt yeah that would be a good idea - you mean an email or something?

**Comment by jpmartinspt** [comment]
@nottrobin e-mail is probably good, I don't mind drafting one.

**Comment by nottrobin** [comment]
It's okay I'll send it, given it's my work.

**Pull request merged**
